targets: msgStart esecutoreComandi msgEnd msgOut

include ../sMakefile

esecutoreComandi: $(SRC)esecutoreComandi.c $(INC)esecutoreComandi.h
	cc  $(SRC)esecutoreComandi.c -o $(BIN)esecutoreComandi

msgOut:
	@echo "I file out.k sono invece contenuti nella directory ./output."
